tests: py: missing json output in meta.t with vlan mapping
Fix this warning due to missing coverage:

 tests/py/any/meta.t.json.got: WARNING: line 2: Wrote JSON equivalent for rule meta mark set vlan id map { 1 : 0x00000001, 4095 : 0x00004095 }
 ERROR: did not find JSON equivalent for rule 'meta mark set vlan id map @map1

Fixes: 8d3de823b622 ("evaluate: reset statement length context before evaluating statement")
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>